#!/bin/sh
# To enable this hook, rename this file to "pre-commit".

echo "increase the version number"
node increaseVersionNumber.js
git add client/public/build_number.txt
git add client/public/build_date.txt